feat: add starknet
lavanet/lava-config pull request #23
Opened 2024-10-30 20:23 UTC by BabyScope

Hi Lava Foundation,

This is my submission for the Starknet Spec Champion. I am almost a year in the community and tried to help where i can. I help the communit as a support member and also running provider and a validator. I also helped with new specs and updated specs where needed. I think with my knowledge and experience i am very capable to be the CHAMPION OF STARKNET SPEC.

Discord : BabyScope

1% - Support and run a provider
0.5% - Inherit, maintain and update Stargaze spec
1% - Benchmarking

2024-11-04 16:49 UTC, RuslanGlaznyov commented
Could you please format JSON to increase readability?

2024-11-05 14:47 UTC, shleikes requested changes

2024-11-05 14:47 UTC, shleikes commented on mainnet-1/specs/starknet.json
You've set some of the APIs compute units from 10 to 20, can you explain why?

2024-11-05 14:47 UTC, shleikes commented on mainnet-1/specs/starknet.json
You are missing v5_0 from the spec

2024-11-05 14:47 UTC, shleikes commented on mainnet-1/specs/starknet.json
> +                    "amount": "15000000000"
The min stake should be 5K

2024-11-06 09:25 UTC, BabyScope commented on benchmarking/Starknet Benchmark
Hi @shleikes,

for benchmarking purpose. Shall i paste it in my comments next time?

2024-11-06 09:38 UTC, BabyScope commented on mainnet-1/specs/starknet.json
> You've set some of the APIs compute units from 10 to 20, can you explain why?

Because of the benchmark
i saw the ones i did a higher are 33% lower calls and also a little more usage of cpu and ram on that calls

2024-11-06 10:57 UTC, shleikes commented on benchmarking/Starknet Benchmark
Thanks for the great work! You can keep the file as it is 😀

2024-11-06 11:25 UTC, shleikes approved these changes

2024-11-06 13:30 UTC, ranlavanet approved these changes

2024-11-12 13:21 UTC, shleikes requested changes

2024-11-12 13:21 UTC, shleikes commented on mainnet-1/specs/starknet.json
> +                            },
Couldn't find this method, both on documentation nor my local pathfinder node

2024-11-17 17:40 UTC, merged